# Local development config
database.url=jdbc:derby:stubserver_db;create=true
database.user=
database.password=
database.schema=APP
database.migration.enabled=true

derbydb.url=jdbc:derby:stubserver_db;create=true

# Table name mappings
stubserver.vstable=STUBSERVERQA_VSDETAILS
stubserver.vscatalogtable=READYAPI_VS_CATALOG
stubserver.executionmode=VS_EXECUTIONMODE
stubserver.liveurl=VS_LIVEURLS
stubserver.metrics=READYAPI_DAILY_METRICS
stubserver.mastercatalogtable=STUBSERVER_MASTER_CATALOG_QA
