IF SCHEMA_ID('${schema}') IS NULL
BEGIN
    EXEC('CREATE SCHEMA ${schema}');
END;

IF OBJECT_ID('${schema}.READYAPI_DAILY_METRICS', 'U') IS NULL
BEGIN
    CREATE TABLE ${schema}.READYAPI_DAILY_METRICS (
        METRICSID       BIGINT NOT NULL,
        TRANSDATE       DATE NOT NULL,
        VSNAME          VARCHAR(150) NULL,
        [COUNT]         BIGINT NULL,
        VIRTSERVERNAME  VARCHAR(50) NULL
            CONSTRAINT DF_READYAPI_DAILY_METRICS_VIRTSERVERNAME DEFAULT '10.44.16.44',
        ENVTYPE         VARCHAR(25) NULL,
        CONSTRAINT PK_READYAPI_DAILY_METRICS PRIMARY KEY (METRICSID)
    );
END;
