IF OBJECT_ID('${schema}.HIBERNATE_ID_GENERATOR', 'U') IS NULL
BEGIN
    CREATE TABLE ${schema}.HIBERNATE_ID_GENERATOR (
        GEN_NAME    VARCHAR(100) NOT NULL,
        GEN_VALUE   BIGINT NOT NULL,
        CONSTRAINT PK_HIBERNATE_ID_GENERATOR PRIMARY KEY (GEN_NAME)
    );
END;

IF NOT EXISTS (
    SELECT 1
    FROM ${schema}.HIBERNATE_ID_GENERATOR
    WHERE GEN_NAME = 'DAILY_METRICS_ID'
)
BEGIN
    INSERT INTO ${schema}.HIBERNATE_ID_GENERATOR (GEN_NAME, GEN_VALUE)
    VALUES ('DAILY_METRICS_ID', 1);
END;
